### ISSUE TITLE
Not defined: defs 

### ISSUE THREAD

**Issue by dallashuggins** [bedrockdata/SchemaParser#1]
What should the variable `defs` be defined as on line 6 (`const schema = defs.ADDITIONAL_FIELDS;`) of the schemaParser.js file?

**Comment by dallashuggins** [comment]
Hi @rlewtwo @jeremysandor - do you know what `defs` should be defined as?

**Comment by jeremysandor** [comment]
Hey @dallashuggins - glad you found this code. We have been using it to help build schemas when they need to be hard coded (ie - no meta data can be pulled from the third party system).

The basic premise is to copy a raw record out of the third party system, copy it here: https://github.com/bedrockdata/SchemaParser/blob/master/schemaParser.js#L46, and a reasonable guess at schema should be returned.

This code was pulled out of a connector that we were working on and I think that the error you are seeing is an artifact of that. @rlewtwo is working on a fix to clarify what this code does and allow it to run on its own.

**Comment by jeremysandor** [comment]
@dallashuggins - to attempt to answer your question more directly - the project could possibly reference a defs file that looks something like this: https://github.com/bedrockdata/quickbooks/blob/master/src/defs.js

**Comment by dallashuggins** [comment]
Hey @jeremysandor - that makes sense, thank you for your quick response! Would it be possible to have my username (`dallashuggins`) or Left Hook's username shared with the Bedrock Data Quickbooks repo? I can't access it currently.

**Comment by jeremysandor** [comment]
@dallashuggins - you should be able to access now

**Comment by dallashuggins** [comment]
@jeremysandor did you share it with my account? I'm still not able to see it. I got the same 404 for Left Hook as well. sorry for the trouble

**Comment by dallashuggins** [comment]
Hi @jeremysandor - sorry to ask, but could you invite me once more? I was testing my Github account and it seems I'm not getting notifications so I changed my settings to send invitations to email and it's working now.
